[mypy]
python_version = 3.12
warn_unused_configs = true
warn_redundant_casts = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
files = vocca

[mypy-vocca.integrations.*]
ignore_errors = true

[mypy-yaml]
ignore_missing_imports = true

[mypy-torch.*]
ignore_missing_imports = true
